name: ws_build

on:
  push:
    branches:
      - main
      - devel


jobs:
  workspace-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          path: workspace
      
      - name: Setup ROS2 workspace
        uses: ichiro-its/ros2-ws-action/setup@v1.0.0
        with:
          distro: humble
      
      - name: Build the workspace
        uses: ichiro-its/ros2-ws-action/build@v1.0.0